language: python
# Target py version 2.6
python:
  - "2.6"
  - "2.7"
  - "3.5"
  - "3.6"

matrix:
  allow_failures:
    - python: "3.5"
    - python: "3.6"
  fast_finish: true

# Pin Ubuntu version to Trusty for Python 2.6 support
dist: trusty

install:
    - "pip install requests"
    - "pip install httmock"

script: nosetests
