language: python
# Target py version 2.6
python:
  - "2.6"

# Pin Ubuntu version to Trusty for Python 2.6 support
dist: trusty

install:
    - "pip install requests"
    - "pip install httmock"

script: nosetests
