language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

install:
    - "pip install requests"
    - "pip install httmock"

script: nosetests

# Cache the dependencies installed by pip
cache: pip
# Avoid pip log from affecting cache
before_cache: rm -fv ~/.cache/pip/log/debug.log
